-   id: mypy
    name: mypy
    description: "Runs mypy over python source.  If you configure additional arguments you'll want to at least."
    entry: mypy
    language: python
    types: [python]
    args: []
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
